EU countries: update energy flows renewable plants
quintel/etsource pull request #2701
Opened 2022-06-02 13:21 UTC by marliekeverweij

- Improved Excel analysis of renewable power plants (see: 20220511_EU_power_plants.xlsx on ETDataset)
- Updated Eurostat table with renewable power plant capacities [NRG_INF_EPCRW__custom_1553298]

2022-06-02 13:44 UTC, Charlottevm approved these changes

2022-06-03 08:03 UTC, mabijkerk requested changes
I think there still is a mistake in the renewables calculation. Looking at Germany for example, there suddenly is no offshore wind power anymore, which does not seem right.

Looking at the Excel source file in the sheet `source renewable - Eurostat` each country in the rows `Summing for power plants in the ETM` seems to link to the wrong column in the rows `ETM categories`. Denmark refers to Germany, Germany to Estonia etc. Each country is draws it source data from the country on the left.

![Screenshot 2022-06-03 at 10 04 55](https://user-images.githubusercontent.com/67338510/171814368-3609a231-a292-4a7e-8231-a85a4d170642.png)

2022-06-07 07:32 UTC, marliekeverweij commented
Sharp @mabijkerk ! I only do not have time to fix this before the deploy today

2022-06-09 13:00 UTC, mabijkerk approved these changes

2022-06-09 14:02 UTC, merged