Ctm etm additional carriers
quintel/etsource pull request #3131
Opened 2024-10-16 11:53 UTC by kaskranenburgQ

This PR adds bio-oil as input-carriers to the industry transformation nodes and adds bio-oil, bio-kerosene and biodiesel as output-carriers to the industry transformation nodes. 

Furthermore it adds an export node of bio-oil, **which exports bio-oil in the form of wood pellets**. This needs to be converted in an issue and needs to be changed in a different project. 

The queries of the following output elements are updated:

- Energy flow overview sankey
- Biomass sankey
- All export output elements
- Feedstock for biogenic energy carriers
- Biomass demand and potential
- Sankey download

Within these output elements the Refinery sankey also needs changes, since we will redesign the Refinery sankey anyway see [ETMODEL #4330](https://github.com/quintel/etmodel/issues/4330), I did not yet pick this up in this PR.

This PR also contains a dataset export update, since the sparse graph queries have been changed to facilitate the export of bio-oil.

To convert to issues:

- [ ] Update refinery sankey with bio-oil 
- [ ] Change export of wood pellets to bio-oil in bio-oil export node.

Goes with: 
[ETModel PR](https://github.com/quintel/etmodel/pull/4351)

2024-10-24 11:54 UTC, kndehaan commented on datasets/AT_austria/graph_values.yml
Note that many graph_values.yml files have this question mark and the ":" spilling over to the next line where they end up next to parent_share. Something going wrong in the export from ETLocal to ETSource? This should be fixed for all datasets where this is happening.

2024-10-24 12:58 UTC, kaskranenburgQ commented on datasets/AT_austria/graph_values.yml
This seems to occur in all datasets for industry chemical non energetic network gas, wood pellets & crude oil shares. 
Would need to investigate further why this happens here.

2024-10-24 14:18 UTC, kndehaan requested changes
Some changes requested, see comments for specific files. But also:

- Chart "Feedstock for biogenic energy carries": the export query misses bio-kerosene and biodiesel

Sankey queries: 
- bio_oil_in_source_of_xxx and bio_oil_to_xxx misses the queries for bio_kerosene, bio_oil and biodiesel, and also an aggregation of biomass products.
- biomass_products_in_source_of_biomass_products should be updated with the new queries. There's not only greengas anymore as biogenic output of transformation node, therefore bio_kerosine, bio_oil and biodiesel (or use aggregation queries biomas_products) should be added. 
- oil_and_derivatives_in_source_of_biomass_products and oil_and_derivatives_to_biomass_products should be updated with the new biogenic carriers, not only greengas anymore
- wood_pellets_in_source_of_xxx and wood_pellets_to_xxx miss the aggregated query of biomass products (which can be used in biomass_products_in_source_of_biomass_products and biomass_products_to_biomass_products queries)

2024-10-25 07:58 UTC, kaskranenburgQ commented on graphs/energy/nodes/energy/energy_export_bio_oil_products.ad
Great observation! I would say we rename it to bio_oil_products_backup. 
It is called bio_oil_products, since it maps the flows export flows of bio-naptha in industry processes.

2024-10-25 09:21 UTC, kaskranenburgQ reviewed
It seems that with this change, it is possible to get a mismatch in the biofuels column when bio-oil is used to create a non-biogenic carrier. This flow from biofuels is then omitted from the chart, see picture below.
<img width="523" alt="Screenshot 2024-10-25 at 11 20 35" src="https://github.com/user-attachments/assets/45ea0b96-7b6d-4070-b944-7e330a0910c6">
In this example, bio-oil is used to create general diesel.
I think it's best to discuss this graph in a dedicated meeting, since it's quite complicated.

2024-10-25 09:25 UTC, kaskranenburgQ commented on gqueries/output_elements/output_series/category_bar_243_biomass_demand/export_of_oily_biomass.gql
The export of these two carriers are represented in the biofuels to export query.
This query can be removed since the export of bio-oil should be represented in that query as well.

2024-10-30 14:37 UTC, merged